namespace ZapClient.Data
{
    public class PathSet
    {
        public bool IsAutogenerated;
        public double[] DeviceRegionCenter;
        public PathNodesInfo PathNodesInfo;
        public int PathDensity;
        public double TravelTime;
        public string PathUUID;
        public int Region;
        public double DeviceRegionRadius;
    }
}
